swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img src=x onerror="alert('123')"><dETAILS open onToGgle=a=prompt,a() x>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
